n44/test4/post/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView

app_name = "post"

urlpatterns = [
    path('list/', post_list, name='post_list'),
    path('list/<str:category>/', post_list, name='category'),
    path('list/detail/<int:pk>/', post_detail, name='post_detail'),

    path('<int:post_pk>/comment/', comment_view, name='comment'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('password-change/', PasswordChangeView.as_view(success_url='done'), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url='/post/password-reset/complete'), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
    path('profile/delete-post/<int:post_id>/', delete_post, name='delete_post'),
    path('profile/edit-post/<int:post_id>/', edit_post, name='edit_post'),
    path('profile/create-post/', create_post, name='create_post'),
    path('profile/account/', create_account, name='create_account'),
]

n44/test4/test4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

n44/test4/post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django_cleanup import cleanup
from django_resized import ResizedImageField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_user')
    reading_time = models.PositiveIntegerField()
    slug = models.SlugField()

    class Status(models.TextChoices):
        DRAFT = 'DR', 'DRAFT'
        REJECTED = 'RJ', 'REJECTED'
        PUBLISHED = 'PB', 'PUBLISHED'
    status = models.CharField(max_length=120, choices=Status.choices, default=Status.DRAFT)

    CATEGORY_CHOICES = (
        ('programming language', 'programming language'),
        ('AI', 'AI'),
        ('frontend', 'frontend'),
        ('backend', 'backend'),
        ('security', 'security'),
        ('others', 'others')
    )

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['status']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for img in self.images.all():
            storage, path = img.image_file.storage, img.image_file.path
            storage.delete(path)
        super().delete(*args, **kwargs)


class Comment(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    creation_time = models.DateTimeField(auto_now=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.title


@ cleanup.select
class Image(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now_add=True)
    image_file = models.ImageField(upload_to='post_images/')

    def name(self):
        return str(self.title) if self.title else str(self.image_file.name)

    def __str__(self):
        return self.name()


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account', blank=True, null=True)
    job = models.CharField(max_length=120, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    photo = ResizedImageField(size=[200, 200], crop=['middle', 'center'], blank=True, null=True)

n44/test4/post/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'text', 'writer']


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='inter password')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='repeat password')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords are not matched!')
        return cd['password2']


class CreatePostForm(forms.ModelForm):
    image2 = forms.ImageField(label='image2', required=False)
    image1 = forms.ImageField(label='image1', required=False)

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['job', 'date_of_birth', 'bio', 'photo']


class SearchForm(forms.Form):
    query = forms.CharField()

n44/test4/post/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import logout

from .models import *
from .forms import *


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    context = {'posts': posts}
    return render(request, 'post/post_list.html', context)


def post_detail(request, pk):
    post = Post.published.get(pk=pk)
    comment = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'comment': comment, 'form': form}
    return render(request, 'post/post_detail.html', context)


def comment_view(request, post_pk):
    if request.method == 'POST':
        post = Post.published.get(pk=post_pk)
        form = CommentForm(request.POST)
        comment = None
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
        context = {'post': post, 'comment': comment, 'form': form}
        return render(request, 'post/comment.html', context)


def log_out(request):
    logout(request)
    return render(request, 'registration/logged_out.html')


def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(Paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {'posts': posts, 'user': user}
    return render(request, 'post/profile.html', context)


def delete_post(request, post_id):
    post = Post.published.get(id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('post:profile')
    else:
        context = {'post': post}
    return render(request, 'post/delete_post.html', context)


def create_post(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post, title=post.title + ' img1')
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post, title=post.title + ' img2')
            return redirect('post:profile')
    else:
        form = CreatePostForm()
    context = {'form': form}
    return render(request, 'post/create_post.html', context)


def edit_post(request, post_id):
    post = Post.published.get(id=post_id)
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post.author = request.user
            post = form.save(commit=False)
            if form.cleaned_data['image1']:
                Image.objects.create(post=post, image_file=form.cleaned_data['image1'])
            if form.cleaned_data['image2']:
                Image.objects.create(post=post, image_file=form.cleaned_data['image2'])
            return redirect('post:profile')
    else:
        form = CreatePostForm(instance=post)
    context = {'form': form, 'post': post}
    return render(request, 'post/create_post.html', context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            form.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'form': form})
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})


def create_account(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        account_form = AccountForm(request.POST, files=request.FILES, instance=request.user.account)
        if user_form.is_valid() and account_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserForm(instance=request.user)
        account_form = AccountForm(instance=request.user.account)
    context = {'user_form': user_form, 'account_form': account_form}
    return render(request, 'post/create_account.html', context)


def search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(title__icontains=query)
    context = {'query': query, 'results': results}
    return render(request, ''. context)

n44/test4/post/templates/post/comment.html
{% extends 'parent/base.html' %}
{% block title %} comment {% endblock %}
{% block content %}
{% if comment %}
<h2>comment is posted successfully!</h2>
<a href="{% url 'post:post_detail' post.pk %}">back to post</a>
{% else %}
<form method="post">
    {{ form.as_p }}
    <input value="post" type="submit">
</form>
{% endif %}
{% endblock %}

n44/test4/post/templates/post/create_account.html
{% extends 'parent/base.html' %}
{% block title %} create account {% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ account_form.as_p }}
    {{ user_form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

n44/test4/post/templates/post/create_post.html
{% extends 'parent/base.html' %}
{% block title %} create post {% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="submit" type="submit">
</form>
{% for img in post.images.all %}
<img src="{{ img.image_file.url }}">
{% endfor %}
{% endblock %}

n44/test4/post/templates/post/delete_post.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
<p> Do you really want to delete '{{ post.title }}' post? </p>
<form method="post">
    {% csrf_token %}
    <input value="yes" type="submit">
    <input value="no" type="submit">
</form>
{% endblock %}

n44/test4/post/templates/post/post_detail.html
{% extends 'parent/base.html' %}
{% block title %} post detail {% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p>{{ post.description|linebreaksbr }}</p>
{% for image in post.images.all %}
<img src="{{ image.image_file.url }}">
{% endfor %}
<center><FONT COLOR="#ff0000"> {{ post.updated_time| date }} </FONT></center>

<h3> comments </h3>
{% for c in comment %}
{{ c.title }} by ({{ c.writer.username }})
<br>
{{ c.text }}
<hr>
{% endfor %}

<form method="post" action="{% url 'post:comment' post.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="submit" type="submit">
</form>
{% endblock %}

n44/test4/post/templates/post/post_list.html
{% extends 'parent/base.html' %}
{% block title %} list {% endblock %}
    {% block content %}
<div style="display: flex; gap: 16px;">
    {% for post in posts %}
    <div style="width: 500px;">
        <a href="{% url 'post:post_detail' post.id %}">{{ post.title }}</a>
        <p>{{ post.description|truncatewords:5 }}</p>
        <img src="{{ post.images.first.image_file.url }} " style="width: 350px; height:225px;">
    </div>
    {% endfor %}
    <br>
{% include 'partials/pagination.html' with page=posts %}
</div>
{% endblock %}

n44/test4/post/templates/post/profile.html
{% extends 'parent/base.html' %}
{% block title %} profile {% endblock %}
{% block content %}
<p><a href="{% url 'post:create_account' %}"> create custom account </a></p>
<table style="width:80%; border: 2px solid black; text-align: left">
    <tr>
        <th> rew </th>
        <th> post title </th>
        <th> edit </th>
        <th> delete </th>
    </tr>
    {% for post in posts %}
    <tr>
        <Td> {{ forloop.counter }} </Td>
        <Td><a href="{% url 'post:post_detail' post.pk %}">{{ post.title }}</a></Td>
        <Td><a href="{% url 'post:edit_post' post.pk %}" > edit </a></Td>
        <Td><a href="{% url 'post:delete_post' post.pk %}"> delete </a></Td>
    </tr>
    {% endfor %}
</table>
{% include 'partials/pagination.html' with page=posts %}
<p><a href="{% url 'post:create_post' %}"> create post </a></p>
<br>
<a href="{% url 'post:password_change' %}"> password change </a>
{% endblock %}